---
apiVersion: v1
kind: Pod
metadata:
  namespace: homework
  name: lesson-2
  labels:
    app: two-containers
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    workingDir: /init
    command: ["wget","https://otus.ru/"]
    volumeMounts:
    - mountPath: /init
      name: shared-volume
  containers:
  - name: web-server
    image: busybox:latest
    workingDir: /homework
    command: ["sh", "-c", "httpd -f -p 8000"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - mountPath: /homework
      name: shared-volume
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]

  volumes:
    - name: shared-volume
      emptyDir:
        sizeLimit: 16Mi
